# Generated by Django 5.2.3 on 2025-06-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='Sheet_name',
            new_name='File_Name',
        ),
    ]
