# Generated by Django 5.2.3 on 2025-06-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_sheet_name_budget_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='title',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='File_Name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
