# Generated by Django 5.2.3 on 2025-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_budget_title_alter_budget_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='About',
            field=models.TextField(default=False),
        ),
    ]
