# Generated by Django 5.2.3 on 2025-06-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_budget_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
                ('WBS_Category', models.FloatField(max_length=100)),
                ('WBS_Code', models.FloatField(max_length=100)),
                ('Total_Budget', models.FloatField(max_length=100)),
                ('April', models.FloatField(max_length=100)),
                ('May', models.FloatField(max_length=100)),
                ('June', models.FloatField(max_length=100)),
                ('July', models.FloatField(max_length=100)),
                ('August', models.FloatField(max_length=100)),
                ('September', models.FloatField(max_length=100)),
                ('October', models.FloatField(max_length=100)),
                ('November', models.FloatField(max_length=100)),
                ('December', models.FloatField(max_length=100)),
                ('January', models.FloatField(max_length=100)),
                ('February', models.FloatField(max_length=100)),
                ('March', models.FloatField(max_length=100)),
            ],
        ),
    ]
