# Generated by Django 5.2.3 on 2025-06-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_excelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelfile',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='April',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='August',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='December',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='February',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='January',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='July',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='June',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='March',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='May',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='November',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='October',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='September',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='Total_Budget',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='WBS_Category',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='WBS_Code',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='april',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='august',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='december',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='february',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='january',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='july',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='june',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='march',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='may',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='november',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='october',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='september',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='total_budget',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='wbs_category',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='wbs_code',
            field=models.FloatField(default=None, null=True),
        ),
    ]
