# Generated by Django 5.2.3 on 2025-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_description_excelfile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='wbs_code',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
